/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.mesinger.dentord.view;

import hr.mesinger.dentord.controller.ObradaPacijent;
import hr.mesinger.dentord.controller.ObradaPosjet;
import hr.mesinger.dentord.controller.ObradaProstorija;
import hr.mesinger.dentord.controller.ObradaStomatolog;
import hr.mesinger.dentord.model.Pacijent;
import hr.mesinger.dentord.model.Posjet;
import hr.mesinger.dentord.model.Prostorija;
import hr.mesinger.dentord.model.Stomatolog;
import hr.mesinger.dentord.util.EdunovaException;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Zvonimir
 */
public class ViewPovijestPosjeta extends javax.swing.JFrame {
    private final ObradaPosjet obrada;
    /**
     * Creates new form ViewPovijestPosjeta
     */
    public ViewPovijestPosjeta() {
        initComponents();
        obrada = new ObradaPosjet();
        
        ucitaj();
        ucitajPacijente();
        ucitajProstorije();
        ucitajStomatologe();
        
    }

    private void ucitaj() {
        
        DefaultListModel<Posjet> m = new DefaultListModel<>();
        obrada.getPodaci().forEach(s->{
            if(s.isIzvrsen()){
            m.addElement(s); 
            }
            
                });
        lstPodaci.setModel(m);
        
        
    }
    private void postaviVrijednosti() {
     
    
        txtareaRazlog.setText(obrada.getEntitet().getRazlog());
        txtareaZahvat.setText(obrada.getEntitet().getZahvat());
        txtTrajaje.setText(obrada.getEntitet().getPredvidenoTrajanje().toString());
        postaviPacijenta();
        postaviProstoriju();
        postaviStomatolog();
        chbIzvrsen.setSelected(obrada.getEntitet().isIzvrsen());
        
        
    
    }
   private void postaviStomatolog() {
        ComboBoxModel<Stomatolog> m = cmbStomatolog.getModel();
        for (int i = 0; i < m.getSize(); i++) {
            if (m.getElementAt(i).getId().equals(
                    obrada.getEntitet().getStomatolog().getId())) {
                cmbStomatolog.setSelectedIndex(i);
                break;
            }   
        }
    }
    private void postaviProstoriju() {
        ComboBoxModel<Prostorija> m = cmbProstorija.getModel();
        for (int i = 0; i < m.getSize(); i++) {
            if (m.getElementAt(i).getId().equals(
                    obrada.getEntitet().getProstorija().getId())) {
                cmbProstorija.setSelectedIndex(i);
                break;
            }   
        }
    }
    private void postaviPacijenta() {
        ComboBoxModel<Pacijent> m = cmbPacijent.getModel();
        for (int i = 0; i < m.getSize(); i++) {
            if (m.getElementAt(i).getId().equals(
                    obrada.getEntitet().getPacijent().getId())) {
                cmbPacijent.setSelectedIndex(i);
                break;
            }   
        }
    }
    
      private void ucitajStomatologe(){
        DefaultComboBoxModel<Stomatolog> m = new DefaultComboBoxModel<>();
         new ObradaStomatolog().getPodaci().forEach(p->m.addElement(p));
            cmbStomatolog.setModel(m);
    }

    private void ucitajProstorije(){
        DefaultComboBoxModel<Prostorija> m = new DefaultComboBoxModel<>();
         new ObradaProstorija().getPodaci().forEach(p->m.addElement(p));
            cmbProstorija.setModel(m);
    }
    private void ucitajPacijente(){
        DefaultComboBoxModel<Pacijent> m = new DefaultComboBoxModel<>();
         new ObradaPacijent().getPodaci().forEach(p->m.addElement(p));
            cmbPacijent.setModel(m);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbStomatolog = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbPacijent = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jlaberl123 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPodaci = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtareaZahvat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareaRazlog = new javax.swing.JTextArea();
        chbIzvrsen = new javax.swing.JCheckBox();
        cmbProstorija = new javax.swing.JComboBox<>();
        btnObrisi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTrajaje = new javax.swing.JTextField();
        btnPovratakUPosjet = new javax.swing.JButton();
        btnPovratak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Prostorija");

        jLabel3.setText("Stomatolog");

        jLabel4.setText("Pacijent");

        jlaberl123.setText("Tretman");

        jLabel1.setText("Razlog");

        lstPodaci.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPodaciValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPodaci);

        txtareaZahvat.setColumns(20);
        txtareaZahvat.setRows(5);
        jScrollPane3.setViewportView(txtareaZahvat);

        txtareaRazlog.setColumns(20);
        txtareaRazlog.setRows(5);
        jScrollPane2.setViewportView(txtareaRazlog);

        chbIzvrsen.setText("Izvršen");
        chbIzvrsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIzvrsenActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jLabel5.setText("Trajanje");

        btnPovratakUPosjet.setText("Povratak u posjet");
        btnPovratakUPosjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPovratakUPosjetActionPerformed(evt);
            }
        });

        btnPovratak.setText("Povratak u izbornik");
        btnPovratak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPovratakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(cmbPacijent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbProstorija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbStomatolog, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlaberl123)
                                    .addComponent(jScrollPane3)
                                    .addComponent(jLabel5)
                                    .addComponent(txtTrajaje)
                                    .addComponent(chbIzvrsen, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 15, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPovratak, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPovratakUPosjet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlaberl123)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbProstorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStomatolog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTrajaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbIzvrsen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPovratakUPosjet, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPovratak, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lstPodaciValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPodaciValueChanged
  
        if (evt.getValueIsAdjusting()) {
            return;
        }
        obrada.setEntitet(lstPodaci.getSelectedValue());
        if (obrada.getEntitet() == null) {
            return;
        }
            postaviVrijednosti();
            
    }//GEN-LAST:event_lstPodaciValueChanged

    private void chbIzvrsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIzvrsenActionPerformed

    }//GEN-LAST:event_chbIzvrsenActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        if (obrada.getEntitet() == null ) {
            JOptionPane.showMessageDialog(null, "Prvo odaberite stavku");
            return;
        }
        try {
            obrada.delete();
            ucitaj();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(null, e.getPoruka());
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnPovratakUPosjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPovratakUPosjetActionPerformed
        new ViewPosjet().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPovratakUPosjetActionPerformed

    private void btnPovratakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPovratakActionPerformed
        new Izbornik().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPovratakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPovratak;
    private javax.swing.JButton btnPovratakUPosjet;
    private javax.swing.JCheckBox chbIzvrsen;
    private javax.swing.JComboBox<Pacijent> cmbPacijent;
    private javax.swing.JComboBox<Prostorija> cmbProstorija;
    private javax.swing.JComboBox<Stomatolog> cmbStomatolog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlaberl123;
    private javax.swing.JList<Posjet> lstPodaci;
    private javax.swing.JTextField txtTrajaje;
    private javax.swing.JTextArea txtareaRazlog;
    private javax.swing.JTextArea txtareaZahvat;
    // End of variables declaration//GEN-END:variables
}
